# Generated by Django 5.2.8 on 2025-11-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Тело подпоста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subposts', to='webapp.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Подпост',
                'verbose_name_plural': 'Подпосты',
                'db_table': 'subposts',
            },
        ),
    ]
